apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.service.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    {{- if eq (include "keycloak.httpsEnabled" .) "true" }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.https }}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
